
services:
  mongo_new:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: '1234'
    ports:
      - "2222:27017"
    volumes:
     - mongo-data:/data/db
    networks:
      - Mynetwork

  nestjs:
    build:
      context: ./backend   
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"  
    env_file:
      - ./backend/.env
    networks:
      - Mynetwork

  vue:
    build:
      context: ./frontend   
      dockerfile: Dockerfile
    ports:
      - "5173:80" 
    networks:
      - Mynetwork

networks:
  Mynetwork:
    driver: bridge

volumes:
  mongo-data:
